# Generated by Django 4.1 on 2025-03-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('firstname',), 'verbose_name_plural': 'actors'},
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
    ]
