# Generated by Django 4.1 on 2025-03-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_actors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemahall',
            options={'ordering': ('name',), 'verbose_name_plural': 'cinemahalls'},
        ),
    ]
