# Generated by Django 4.1 on 2025-03-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_cinemahall_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='cinema.genre'),
        ),
    ]
