# Generated by Django 4.1 on 2025-03-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('first_name',), 'verbose_name_plural': 'actors'},
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
