# Generated by Django 4.1 on 2025-03-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_movie_actors_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemahall',
            options={'ordering': ('name',), 'verbose_name_plural': 'cinema_halls'},
        ),
    ]
